layout_spectrum: 0.49866990908049047
typography_spectrum: 0.9598961742594838
color:
  brandColors:
    - '#FFFFFF'
    - '#2A2A2A'
    - '#939293'
    - '#915D44'
    - '#CC8C54'
  brandStrength: 0.8573007944505662
  lightness: 0.3795535983517766
  saturation: 0.4704265114851296
  rhythmicContrast: 0.6545701518189162
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jennifer Jackson
  email: jennifer@literacyladders.com
  url: literacyladders
name: literacyladders
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Welcome to Literacy Ladders!
    id: e7585918-6476-42b3-bdfa-07f4a7665294
    type: content
  - name: 'Blog: "Stickers are banned from my house!"'
    id: 6fe9d1ec-5e12-4e4b-b493-9f060958d6f6
    type: content
favicon: null
title: Welcome to Literacy Ladders!
description: Climb high. Dive deep.
purpose: []
