typography_spectrum: 0.6223564422689378
color:
  brandColors:
    - '#fdfae9'
    - '#c09b6f'
    - '#241125'
    - '#c52027'
    - '#3da477'
  brandStrength: 0.26591191068291664
  lightness: 0.9579885380808264
  saturation: 0.1932431454770267
  rhythmicContrast: 0.2923810235224664
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25089
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jennifer Jackson
  email: jennifer@literacyladders.com
  url: literacyladders
name: literacyladders
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Welcome to Literacy Ladders!
    id: e7585918-6476-42b3-bdfa-07f4a7665294
    type: content
  - name: 'Blog: "Stickers are banned from my house!"'
    id: 6fe9d1ec-5e12-4e4b-b493-9f060958d6f6
    type: content
favicon: null
title: Welcome to Literacy Ladders!
purpose: []
